"use client"
import { FormEvent, useEffect, useState } from "react"
import { Pencil, Plus, Trash2 } from "lucide-react"
import { DashboardShell } from "@/components/dashboard-shell"
import { Button } from "@/components/ui/button"

type Place = { id: number; name: string; latitude: number; longitude: number; is_active: boolean }
const empty = { name: "", latitude: "", longitude: "" }
function error_text(data: unknown) { if (data && typeof data === "object" && "detail" in data) return String((data as { detail: unknown }).detail); return "Unable to complete that request." }
function notify_known_places_updated() { window.dispatchEvent(new Event("known-places-updated")); if (typeof BroadcastChannel !== "undefined") { const channel = new BroadcastChannel("known-places-updated"); channel.postMessage(null); window.setTimeout(() => channel.close(), 0) } }

export default function PlacesPage() {
  const [places, set_places] = useState<Place[]>([]); const [form, set_form] = useState(empty); const [editing, set_editing] = useState<number | null>(null); const [error, set_error] = useState("")
  async function load() { const r = await fetch("/api/monitoring/known-places?include_inactive=true"); if (r.ok) set_places(await r.json()) }
  useEffect(() => { void load() }, [])
  async function submit(event: FormEvent) { event.preventDefault(); set_error(""); const url = editing ? `/api/monitoring/known-places/${editing}` : "/api/monitoring/known-places"; const r = await fetch(url, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, latitude: Number(form.latitude), longitude: Number(form.longitude) }) }); if (!r.ok) { set_error(error_text(await r.json())); return }; set_form(empty); set_editing(null); notify_known_places_updated(); void load() }
  async function remove(id: number) { if (!window.confirm("Remove this place from active place lists?")) return; const r = await fetch(`/api/monitoring/known-places/${id}`, { method: "DELETE" }); if (!r.ok) set_error(error_text(await r.json())); else { notify_known_places_updated(); void load() } }
  return <DashboardShell title="Known places" description="Manage the places available to incident workflows."><div className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="h-fit rounded-xl border border-[#dce4ef] bg-white p-5 shadow-sm"><h2 className="font-semibold">{editing ? "Edit place" : "Add place"}</h2>{["name", "latitude", "longitude"].map((field) => <label key={field} className="mt-4 block text-sm font-medium capitalize">{field} <span className="text-[#DC2626]">*</span><input required value={form[field as keyof typeof form]} type={field === "name" ? "text" : "number"} step={field === "name" ? undefined : "0.000001"} min={field === "latitude" ? -90 : field === "longitude" ? -180 : undefined} max={field === "latitude" ? 90 : field === "longitude" ? 180 : undefined} onChange={(e) => set_form({ ...form, [field]: e.target.value })} className="mt-1 w-full rounded-lg border border-[#b9cdeb] px-3 py-2 outline-none focus:ring-2 focus:ring-[#60A5FA]" /> </label>)}{error && <p className="mt-3 text-sm text-[#DC2626]">{error}</p>}<div className="mt-5 flex gap-2"><Button type="submit"><Plus className="size-4" />{editing ? "Save changes" : "Add place"}</Button>{editing && <Button type="button" variant="outline" onClick={() => { set_editing(null); set_form(empty) }}>Cancel</Button>}</div></form><section className="overflow-hidden rounded-xl border border-[#dce4ef] bg-white shadow-sm"><div className="border-b border-[#dce4ef] px-5 py-4"><h2 className="font-semibold">Places</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#eef5ff] text-[#607694]"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Latitude</th><th className="px-5 py-3">Longitude</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Actions</th></tr></thead><tbody>{places.map((p) => <tr key={p.id} className="border-t border-[#edf1f6]"><td className="px-5 py-4 font-medium">{p.name}</td><td className="px-5 py-4">{p.latitude}</td><td className="px-5 py-4">{p.longitude}</td><td className="px-5 py-4">{p.is_active ? "Active" : "Inactive"}</td><td className="px-5 py-4"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => { set_editing(p.id); set_form({ name: p.name, latitude: String(p.latitude), longitude: String(p.longitude) }) }}><Pencil className="size-3" />Edit</Button>{p.is_active && <Button size="sm" variant="destructive" onClick={() => void remove(p.id)}><Trash2 className="size-3" />Delete</Button>}</div></td></tr>)}</tbody></table></div></section></div></DashboardShell>
}
